### ISSUE TITLE
Experiments get moved to RC-001S RGU

### ISSUE THREAD

**Issue by uxlapogi** [WaveFunctionP/ForScience#5]
Stored experiments keep getting moved to the RGU probe core. As a workaround disabling FS works if I want to have the experiments stored somewhere else.

I ran into trouble getting my experiments off of my space station, and the RGU kept snagging my stuff.

I also can't redirect the target of the experiment collection. Selecting a docked command pod and "control from here" still moves the stuff to the RGU.

Is this intended behavior?

**Comment by WaveFunctionP** [comment]
Turning it off when you want to do something manually is indeed the intended behavior.

Because I can not know what your intention is for docking or separation, and the part graph is unpredictable, the mod makes no assumptions and merely choose the first science container it comes across in the part tree as the storage container. Most of the time, this is the one and only command pod.

If you have more complicated needs, I believe there is still Automated Science Sampler or Science Alert which may suit you use case more. You can add or remove ForScience! at any time. It will not break your saved file to remove it should you decide that you don't like it. And you can add it back any time without issue.

**Comment by uxlapogi** [comment]
Thanks!
Switched over to Automated Science Sampler for now, since I'm worried I forget to turn FS back on when I'm done managing the station experiments.
